/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   msh_errors_cd.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: roruiz-v <roruiz-v@student.42malaga.com    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/02/11 14:51:40 by roruiz-v          #+#    #+#             */
/*   Updated: 2024/02/11 14:51:54 by roruiz-v         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

/**
 * @brief  **  ERRORS GENERATED BY BUILTIN 'CD'  **
 *    (it's not necessary to handly-manipulate 'data->exit' here)
 * @param data 
 * @param error 
 */
void	ft_error_cd(t_msh *data, t_cmd *cmd_nd, int error)
{
	if (error == ERROR_CHDIR_FAILURE)
	{
		ft_putstr_fd("msh: cd: ", 2);
		ft_putstr_fd(cmd_nd->c_args[1], 2);
		ft_putstr_fd(": No such file or directory\n", 2);
		error = NO_ERROR;
		data->exit_code = 1;
	}
	else if (error == ERROR_CHDIR_OLDPWD_NOT_SET)
	{
		ft_putstr_fd("msh: cd: OLDPWD not set\n", 2);
		error = NO_ERROR;
		data->exit_code = 1;
	}
	else if (error == ERROR_CHDIR_HOME_NOT_SET)
	{
		ft_putstr_fd("msh: cd: HOME not set\n", 2);
		error = NO_ERROR;
	}
}
