/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   msh_errors.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: roruiz-v <roruiz-v@student.42malaga.com    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/11/01 15:30:00 by roruiz-v          #+#    #+#             */
/*   Updated: 2024/02/11 14:32:06 by roruiz-v         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

void	ft_error_status(t_msh *data, t_cmd *cmd_nd, int error)
{
	if (error == END)
		data->error = END;
	else if (error == ERROR_NO_PATHS)
	{
		ft_putstr_fd("Error: PATH doesn't exist\n", 2);
		data->error = NO_ERROR;
	}
	else if (error == ERROR_CMD_NOT_EXISTS)
	{
		ft_putstr_fd("msh: ", 2);
		ft_putstr_fd(cmd_nd->c_args[0], 2);
		ft_putstr_fd(": command not found\n", 2);
		data->error = NO_ERROR;
		data->exit_code = 127;
	}
	else if (error == ERROR_TOO_MANY_ARGUMENTS)
	{
		ft_putstr_fd("msh: exit: too many arguments\n", 2);
		data->exit_code = 1;
		data->error = NO_ERROR;
	}
}

void	ft_error_pipes_forks(t_msh *data, int error)
{
	if (error == ERROR_PID)
	{
		ft_putstr_fd("Error: PID\n", 2);
		data->error = END;
	}
	else if (error == ERROR_PIPE_CREATION)
	{
		ft_putstr_fd("Error: pipe \n", 2);
		data->error = END;
	}
	else if (error == ERROR_PIPE_EXECUTION)
	{
		ft_putstr_fd("Error: pipe execution command error\n", 2);
		data->error = END;
	}
}

/**
 * @brief  **  ERRORS GENERATED BY BUILTIN 'CD'  **
 *    (it's not necessary to handly-manipulate 'data->exit' here)
 * @param data 
 * @param error 
 */
void	ft_error_cd(t_msh *data, t_cmd *cmd_nd, int error)
{
	if (error == ERROR_CHDIR_FAILURE)
	{
		ft_putstr_fd("msh: cd: ", 2);
		ft_putstr_fd(cmd_nd->c_args[1], 2);
		ft_putstr_fd(": No such file or directory\n", 2);
		error = NO_ERROR;
		data->exit_code = 1;
	}
	else if (error == ERROR_CHDIR_OLDPWD_NOT_SET)
	{
		ft_putstr_fd("msh: cd: OLDPWD not set\n", 2);
		error = NO_ERROR;
		data->exit_code = 1;
	}
	else if (error == ERROR_CHDIR_HOME_NOT_SET)
	{
		ft_putstr_fd("msh: cd: HOME not set\n", 2);
		error = NO_ERROR;
	}
}

void	ft_error_export(t_msh *data, char *nm, int error)
{
	if (error == ERROR_INVALID_EXPORT_IDENTIFIER)
	{
		ft_putstr("msh: export: `", 2);
		ft_putstr(nm, 2);
		ft_putstr("': not a valid identifier\n", 2);
		error = NO_ERROR;
		data->exit_code = 1;
	}
}

void	ft_error_files(t_msh *data, t_cmd *cmd_nd, t_rd *rd_nd, int error)
{
	if (error == ERROR_OPEN_INFILE)
	{
		ft_putstr_fd("msh: ", 2);
		ft_putstr_fd(rd_nd->file, 2);
		ft_putstr_fd(" : No such file or directory\n", 2);
		data->exit_code = 1;
	}
	else if (error == ERROR_OPEN_OUTFILE)
	{
		ft_putstr_fd("msh: ", 2);
		ft_putstr_fd(" : Permission denied\n", 2);
		data->exit_code = 1;
	}
	else if (error == ERROR_NO_SUCH_FILE_OR_DIRECTORY)
	{
		if (ft_strcmp(cmd_nd->c_args[0], "env") != 0)
			ft_putstr_fd("msh: ", 2);
		ft_putstr_fd(cmd_nd->c_args[0], 2);
		ft_putstr_fd(": ", 2);
		if (cmd_nd->c_args[1])
			ft_putstr_fd(cmd_nd->c_args[1], 2);
		ft_putstr_fd(": No such file or directory\n", 2);
		data->exit_code = 127;
		data->error = NO_ERROR;
	}
}

void	ft_error_cmds(t_msh *data, t_cmd *cmd_nd, int error)
{
	if (error == ERROR_CMD_NOT_EXISTS)
	{
		ft_putstr_fd("msh: ", 2);
		ft_putstr_fd(cmd_nd->c_args[0], 2);
		ft_putstr_fd(": command not found\n", 2);
		data->exit_code = 127;
	}
	else if (error == ERROR_CMD_NOT_EXECUTABLE)
	{
		ft_putstr_fd("msh: ", 2);
		ft_putstr_fd(cmd_nd->c_args[0], 2);
		ft_putstr_fd(": Permission denied\n", 2);
		data->exit_code = 126;
	}
	else if (error == ERROR_NO_PERMISSION)
	{
		ft_putstr_fd(cmd_nd->c_args[0], 2);
		ft_putstr_fd(": permission denied: ", 2);
		ft_putstr_fd("\n", 2);
		data->exit_code = 1;
	}
}
